# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# org.gradle.parallel=true

# AndroidX
android.useAndroidX=true

# Build cache
org.gradle.caching=true

# Don't fail build on lint errors (lint is run separately)
android.abortOnLintError=false
android.disableLintResourceNsChecks=true

# Compatibility
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
